global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'lsst-prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'lsst-kafka-exporter'
    static_configs:
      - targets: ['kafka-exporter:9308']

  - job_name: 'lsst-prometheus-jmx-exporter'
    scrape_interval: 10s
    static_configs:
      - targets: ['broker1:7071']
